apiVersion: v1
data:
  config.yaml: |
    branch-protection:
      protect-tested-repos: true
    github:
      LinkURL: null
    in_repo_config:
      enabled:
        spaily-inc/gohttp: true
        spaily-inc/golang: true
        spaily-inc/node-http: true
        spaily-inc/nody: true
        spaily/jx3-kubernetes: true
    plank: {}
    pod_namespace: jx
    prowjob_namespace: jx
    push_gateway:
      serve_metrics: true
    tide:
      context_options:
        from-branch-protection: true
        required-if-present-contexts: null
        skip-unknown-contexts: false
      merge_method:
        spaily-inc/gohttp: merge
        spaily-inc/golang: merge
        spaily-inc/node-http: merge
        spaily-inc/nody: merge
        spaily/jx3-kubernetes: merge
      queries:
      - labels:
        - approved
        missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/work-in-progress
        - needs-ok-to-test
        - needs-rebase
        repos:
        - spaily/jx3-kubernetes
        - spaily-inc/gohttp
        - spaily-inc/golang
        - spaily-inc/node-http
        - spaily-inc/nody
      - labels:
        - updatebot
        missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/work-in-progress
        - needs-ok-to-test
        - needs-rebase
        repos:
        - spaily/jx3-kubernetes
        - spaily-inc/gohttp
        - spaily-inc/golang
        - spaily-inc/node-http
        - spaily-inc/nody
      target_url: http://lighthouse-jx.192.168.1.80.nip.io/merge/status
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: config
  namespace: jx
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
