apiVersion: jenkins.io/v1
kind: SourceRepository
metadata:
  creationTimestamp: null
  labels:
    owner: spaily-inc
    provider: github
    repository: gohttp
    gitops.jenkins-x.io/pipeline: 'namespaces'
  name: spaily-inc-gohttp
  namespace: jx
spec:
  httpCloneURL: https://github.com/spaily-inc/gohttp.git
  org: spaily-inc
  provider: https://github.com
  providerKind: github
  providerName: github
  repo: gohttp
  scheduler:
    kind: ""
    name: in-repo
  url: https://github.com/spaily-inc/gohttp
